services:
  cfc-lab-1-db:
    build: ./db
    container_name: cfc-lab-1-redis


  cfc-lab-1-app:
    build: ./app
    container_name: cfc-lab-1-app
    ports:
      - "5000:5000"
    depends_on:
      - cfc-lab-1-db